"""Add hash field to Media

Revision ID: 41d535e25194
Revises: c55a287f2973
Create Date: 2025-12-16 10:16:05.711830

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '41d535e25194'
down_revision: Union[str, Sequence[str], None] = 'c55a287f2973'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('media', sa.Column('original_filename', sa.String(length=255), nullable=False))
    op.add_column('media', sa.Column('storage_filename', sa.String(length=255), nullable=False))
    op.create_unique_constraint(None, 'media', ['storage_filename'])
    op.drop_column('media', 'filename')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('media', sa.Column('filename', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=False))
    op.drop_constraint(None, 'media', type_='unique')
    op.drop_column('media', 'storage_filename')
    op.drop_column('media', 'original_filename')
    # ### end Alembic commands ###
