"""Add new column to User

Revision ID: 935e7fef7dc1
Revises: 0d6cc16bae0a
Create Date: 2025-12-04 20:21:16.695006

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '935e7fef7dc1'
down_revision: Union[str, Sequence[str], None] = '0d6cc16bae0a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invoices', sa.Column('is_paid', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('invoices', 'is_paid')
    # ### end Alembic commands ###
