"""Update class columns

Revision ID: ad3b59679739
Revises: 935e7fef7dc1
Create Date: 2025-12-04 20:28:44.921325

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ad3b59679739'
down_revision: Union[str, Sequence[str], None] = '935e7fef7dc1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('class_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'users', 'student_classes', ['class_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'class_id')
    # ### end Alembic commands ###
