name: CI

on:
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      ENV: test

    services:
      mysql:
        image: mysql:8
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: test_db
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.14'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements/requirements-test.txt
          
      - name: Wait for MySQL to be ready
        run: |
          for i in {1..30}; do
            mysqladmin ping -h127.0.0.1 -uroot -proot && break
            echo "Waiting for MySQL..."
            sleep 2
          done


        
      - name: Load CI environment
        run: |
          set -o allexport
          source  $GITHUB_WORKSPACE/.env.test.github
          set +o allexport

      - name: Print environment variables
        run: |
          echo "ENV=$ENV"
          echo "MYSQL_DB_USER=$MYSQL_DB_USER"
          echo "MYSQL_DB_PASSWORD=$MYSQL_DB_PASSWORD"
          echo "MYSQL_DB_HOST=$MYSQL_DB_HOST"
          echo "MYSQL_DB_NAME=$MYSQL_DB_NAME"
          echo "MYSQL_DB_PORT=$MYSQL_DB_PORT"

      - name: Run Alembic migrations
        run: alembic upgrade head

      - name: Lint code with Pylint
        run: pylint app tests  --disable=R,C,W

      - name: Run tests
        run: pytest --maxfail=1 --disable-warnings -v
